# Color scheme TOML
# Colors are represented as
# [int r, int g, int b]
# use an array of colors to represent a color scheme


[trans]
colors = [[91,206,250],[245,169,184],[255,255,255],[245,169,184],[91,206,250]]
alias = ["transgender"]